SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT MEMBER_ID, COUNT(*) AS CNT 
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID) AS REVIEW_CNT
    WHERE CNT = (
        SELECT MAX(CNT) FROM (
        SELECT MEMBER_ID, COUNT(*) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) AS MAX_REVIEW_CNT))
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;
