WITH Eligible_Cars AS (
    -- 8월~10월 동안 5회 이상 대여된 자동차를 필터링
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT 
    MONTH(START_DATE) AS RENTAL_MONTH,  -- 해당 월 추출
    CAR_ID,
    COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'  -- 다시 8~10월 범위 필터링
AND CAR_ID IN (SELECT CAR_ID FROM Eligible_Cars)  -- 5회 이상 대여된 자동차만 포함
GROUP BY RENTAL_MONTH, CAR_ID
ORDER BY RENTAL_MONTH ASC, CAR_ID DESC;
