SELECT CONCAT("/home/grep/src/",BOARD_ID,"/",FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH
FROM  USED_GOODS_FILE
WHERE BOARD_ID = (SELECT BOARD_ID
                FROM USED_GOODS_BOARD
                WHERE VIEWS = (SELECT MAX(VIEWS)
                FROM USED_GOODS_BOARD))
ORDER BY FILE_ID DESC;



-- CONCAT("/home/grep/src/",B.BOARD_ID,"/",F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH