SELECT FOOD_PRODUCT.CATEGORY, FOOD_PRODUCT.PRICE AS MAX_PRICE, FOOD_PRODUCT.PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) AS MAX_P
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY) AS GROUP_FOOD
JOIN FOOD_PRODUCT
ON FOOD_PRODUCT.CATEGORY = GROUP_FOOD.CATEGORY
WHERE FOOD_PRODUCT.PRICE = GROUP_FOOD.MAX_P
ORDER BY 2 DESC;



-- WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'